name: Event PR - Single Job

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - name: Labeling
        run: echo "Labeling event triggered!"

  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello, world!"