name: Event PR - Single Job

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - name: Print event information
        run: |
          echo "Labeling event triggered!"
          echo "Action: ${{ github.event.action }}"
          echo "Label: ${{ github.event.label.name }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"

  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello, world!"
