name: First Action

on:
  workflow_dispatch:
    inputs:
      debug_mode:
        type: boolean
        description: 'Debug mode'
        default: false
        required: false
      sample_value:
        type: string
        description: 'cualquier valor'
        default: ''
        required: false

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello, world!"
      - name: Hello maquina
        run: echo "Hello, maquina!"
  say_bye:
    runs-on: ubuntu-latest
    needs: say_hello
    steps:
      - name: bye world
        run: echo "bye, world!"
      - name: bye maquina
        run: echo ${{ github.event.inputs.debug_mode }}
  

